//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iRacingIL.WebSiteWebForms
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class iracingilEntities : DbContext
    {
        public iracingilEntities()
            : base("name=iracingilEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<driver> drivers { get; set; }
        public virtual DbSet<incident_drivers> incident_drivers { get; set; }
        public virtual DbSet<incident_final_results> incident_final_results { get; set; }
        public virtual DbSet<incident_stuart_result> incident_stuart_result { get; set; }
        public virtual DbSet<incident_stuarts> incident_stuarts { get; set; }
        public virtual DbSet<incident> incidents { get; set; }
        public virtual DbSet<race> races { get; set; }
        public virtual DbSet<track> tracks { get; set; }
        public virtual DbSet<raceresult> raceresults { get; set; }
        public virtual DbSet<season> seasons { get; set; }
    }
}
