//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iRacingIL.WebSiteWebForms
{
    using System;
    using System.Collections.Generic;
    
    public partial class incident_drivers
    {
        public int idincident_driversid { get; set; }
        public int incidentid { get; set; }
        public int driverid { get; set; }
        public string response { get; set; }
    
        public virtual incident incident { get; set; }
        public virtual driver driver { get; set; }
    }
}
