//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iRacingIL.WebSiteWebForms
{
    using System;
    using System.Collections.Generic;
    
    public partial class race
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public race()
        {
            this.incidents = new HashSet<incident>();
            this.raceresults = new HashSet<raceresult>();
        }
    
        public int raceid { get; set; }
        public int seasonid { get; set; }
        public int racenumber { get; set; }
        public int trackid { get; set; }
        public byte israced { get; set; }
        public string youtubeurl { get; set; }
        public System.DateTime when { get; set; }
        public string imgurl { get; set; }
        public byte stuartsassigned { get; set; }
        public byte israceclosed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<incident> incidents { get; set; }
        public virtual track track { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<raceresult> raceresults { get; set; }
        public virtual season season { get; set; }
    }
}
